server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ymzxiztfoagyju:a8b2aaf7d043a174bf30d4b89713d28a56f7b572e256b4865b6741e650bd11fd@ec2-34-230-115-172.compute-1.amazonaws.com:5432/dfgntpr2tvml7m
    username: ymzxiztfoagyju
    password: a8b2aaf7d043a174bf30d4b89713d28a56f7b572e256b4865b6741e650bd11fd
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none


application:
  description: Projeto criado para o bootcamp DIO - Santander